### ISSUE TITLE
Configurable music request channel

### ISSUE THREAD

**Issue by TobiTenno** [simonknittel/discord-bot-api#30]
Allow a configuration where the bot only takes requests from specified channels.

If the config is empty for it, allow all channels.

**Comment by simonknittel** [comment]
Sounds like a good idea.

I think it's always better to be able to config as much stuff as possible :D

**Comment by simonknittel** [comment]
Added it as general option for every command. It's part of v0.7.7. Please check if it's working as expected for you.

Here is the part of the changelog:
- You can now specify a channel which is required to request a command
  - Example:
  
  ``` json
  "plugins": {
      "music-bot": {
          "commands": {
              "add": {
                  "channel": "#music"
              }
          }
      }
  }
  ```
